### ISSUE TITLE
Unable to load application: Bundler::GemRequireError: There was an error while trying to load the gem 'pghero'.

### ISSUE THREAD

**Issue by gionn** [bmorton/pghero_solo#6]
```
$ docker run -ti -e DATABASE_URL=postgres://postgres@cloudesire_pg_1:5432/cloudesire-test -p 8080:8080 bmorton/pghero
Unable to find image 'bmorton/pghero:latest' locally
latest: Pulling from bmorton/pghero
fdd5d7827f33: Already exists 
a3ed95caeb02: Pull complete 
0f35d0fe50cc: Already exists 
627b6479c8f7: Pull complete 
67c44324f4e3: Pull complete 
1429c50af3b7: Pull complete 
8207a1b09d34: Pull complete 
f4fd1f72cd2a: Pull complete 
8c4074b3c552: Pull complete 
33a1a12cf968: Pull complete 
218d4bcdc54a: Pull complete 
12da0cc15b1c: Pull complete 
e21a9abeb878: Pull complete 
6f395257d58d: Pull complete 
Digest: sha256:eb18bea3b83c938dec5f0a3449b535c79bb939a47b39dd11db80996986f5b3f4
Status: Downloaded newer image for bmorton/pghero:latest
[6] Puma starting in cluster mode...
[6] * Version 3.0.2 (ruby 2.3.0-p0), codename: Plethora of Penguin Pinatas
[6] * Min threads: 8, max threads: 12
[6] * Environment: production
[6] * Process workers: 1
[6] * Preloading application
[6] ! Unable to load application: Bundler::GemRequireError: There was an error while trying to load the gem 'pghero'.
/usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:80:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'pghero'. (Bundler::GemRequireError)
        from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
        from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
        from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
        from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
        from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
        from /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
        from config.ru:1:in `block in <main>'
        from /usr/local/bundle/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
        from /usr/local/bundle/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
        from config.ru:in `new'
        from config.ru:in `<main>'
        from /usr/local/bundle/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
        from /usr/local/bundle/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
        from /usr/local/bundle/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
        from /usr/local/bundle/gems/puma-3.0.2/lib/puma/configuration.rb:310:in `load_rackup'
        from /usr/local/bundle/gems/puma-3.0.2/lib/puma/configuration.rb:239:in `app'
        from /usr/local/bundle/gems/puma-3.0.2/lib/puma/runner.rb:119:in `load_and_bind'
        from /usr/local/bundle/gems/puma-3.0.2/lib/puma/cluster.rb:361:in `run'
        from /usr/local/bundle/gems/puma-3.0.2/lib/puma/launcher.rb:173:in `run'
        from /usr/local/bundle/gems/puma-3.0.2/lib/puma/cli.rb:74:in `run'
        from /usr/local/bundle/gems/puma-3.0.2/bin/puma:10:in `<top (required)>'
        from /usr/local/bundle/bin/puma:16:in `load'
        from /usr/local/bundle/bin/puma:16:in `<main>'
```

**Comment by bmorton** [comment]
Interesting.  Let me take a look.

**Comment by bmorton** [comment]
Weird, I get a few warnings, but no bundler issues:

```
haushinka:~$ docker run -ti -e DATABASE_URL=postgres://postgres:mysecretpassword@localhost:5432/postgres -p 8080:8080 bmorton/pghero
Unable to find image 'bmorton/pghero:latest' locally
latest: Pulling from bmorton/pghero
fdd5d7827f33: Already exists
a3ed95caeb02: Already exists
0f35d0fe50cc: Already exists
627b6479c8f7: Already exists
67c44324f4e3: Already exists
1429c50af3b7: Already exists
8207a1b09d34: Already exists
f4fd1f72cd2a: Already exists
8c4074b3c552: Already exists
33a1a12cf968: Pull complete
218d4bcdc54a: Pull complete
12da0cc15b1c: Pull complete
e21a9abeb878: Pull complete
6f395257d58d: Pull complete
Digest: sha256:eb18bea3b83c938dec5f0a3449b535c79bb939a47b39dd11db80996986f5b3f4
Status: Downloaded newer image for bmorton/pghero:latest
[7] Puma starting in cluster mode...
[7] * Version 3.0.2 (ruby 2.3.0-p0), codename: Plethora of Penguin Pinatas
[7] * Min threads: 8, max threads: 12
[7] * Environment: production
[7] * Process workers: 1
[7] * Preloading application
DEPRECATION WARNING: You did not specify a `log_level` in `production.rb`. Currently, the default value for `log_level` is `:info` for the production environment and `:debug` in all other environments. In Rails 5 the default value will be unified to `:debug` across all environments. To preserve the current setting, add the following line to your `production.rb`:

   config.log_level = :info

. (called from block in tsort_each at /usr/local/lib/ruby/2.3.0/tsort.rb:228)
[7] * Listening on tcp://0.0.0.0:8080
[7] Use Ctrl-C to stop
[7] - Worker 0 (pid: 10) booted, phase: 0
```

**Comment by manuelmazzuola** [comment]
@gionn 
Are you sure that your connection string is correct?
Try with `postgres://postgres:yourpassword@localhost:5432/yourdbname`

**Comment by gionn** [comment]
Yeah, password was clearly missing, but didn't change anything adding it.
Then, I realized to have forgot to run the container in the same network of the postgres container, but again, nothing changed.

Finally, I tried this approach:
```
$ docker run -ti --net=host -e DATABASE_URL=postgres://postgres:admin@localhost:5432/cloudesire-test -p 8080:8080 bmorton/pghero
[6] Puma starting in cluster mode...
[6] * Version 3.0.2 (ruby 2.3.0-p0), codename: Plethora of Penguin Pinatas
[6] * Min threads: 8, max threads: 12
[6] * Environment: production
[6] * Process workers: 1
[6] * Preloading application
DEPRECATION WARNING: You did not specify a `log_level` in `production.rb`. Currently, the default value for `log_level` is `:info` for the production environment and `:debug` in all $ther environments. In Rails 5 the default value will be unified to `:debug` across all environments. To preserve the current setting, add the following line to your `production.rb`:

   config.log_level = :info

. (called from block in tsort_each at /usr/local/lib/ruby/2.3.0/tsort.rb:228)
[6] * Listening on tcp://0.0.0.0:8080
[6] Use Ctrl-C to stop
[6] - Worker 0 (pid: 9) booted, phase: 0
```

It's crazy, but it's look like that putting the `_` character in the hostname trigger such error:

```
docker run -ti --net=host -e DATABASE_URL=postgres://postgres:admin@localhost_:5432/cloudesire-test -p 8080:8080 bmorton/pghero
```

**Comment by DexterTheDragon** [comment]
The `_` is not a valid hostname character.

> Hostnames are composed of series of labels concatenated with dots, as are all domain names. For example, "en.wikipedia.org" is a hostname. Each label must be between 1 and 63 characters long,[2] and the entire hostname (including the delimiting dots but not a trailing dot) has a maximum of 253 ASCII characters.[3]

> The Internet standards (Requests for Comments) for protocols mandate that component hostname labels may contain only the ASCII letters 'a' through 'z' (in a case-insensitive manner), the digits '0' through '9', and the hyphen ('-'). The original specification of hostnames in RFC 952, mandated that labels could not start with a digit or with a hyphen, and must not end with a hyphen. However, a subsequent specification (RFC 1123) permitted hostname labels to start with digits. No other symbols, punctuation characters, or white space are permitted.

[source](https://en.wikipedia.org/wiki/Hostname)

**Comment by manuelmazzuola** [comment]
@gionn https://github.com/docker/compose/issues/229

**Comment by gionn** [comment]
Argh, so I must override container names in my docker-compose, nice.

Thanks everyone.
